# Conf file to load audio-driver modules at boot-up time
# Install under /etc/modules-load.d/ path
# QRB4210.LE.2.0 Bengal Audioreach

# DSP & IPC Core Framework
q6_pdr_dlkm
q6_notifier_dlkm
q6_dlkm
snd_event_dlkm
gpr_dlkm
spf_core_dlkm
audpkt_ion_dlkm
audio_pkt_dlkm
adsp_loader_dlkm
audio_prm_dlkm

# SoC Bus & Controllers
pinctrl_lpi_dlkm
swr_dlkm
swr_ctrl_dlkm

# Audio Codecs
stub_dlkm
wcd_core_dlkm
wcd9xxx_dlkm
mbhc_dlkm
wcd937x_slave_dlkm
wcd937x_dlkm
wsa881x_analog_dlkm
pm2250_spmi_dlkm
rouleur_slave_dlkm
rouleur_dlkm

# Bolero CDC Macros
bolero_cdc_dlkm
va_macro_dlkm
rx_macro_dlkm
tx_macro_dlkm

# Sound Card Registration (Machine Driver)
machine_dlkm

