#! /bin/sh
# Copyright (c) 2019, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


export MODULE_BASE=/lib/modules/`uname -r`/
set -e

case "$1" in
  start)
        echo -n "Starting/Loading audio module: "

        echo "audio:start/load" > /dev/kmsg
	insmod $MODULE_BASE/kernel/techpack/audio/soc/snd_event_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/soc/pinctrl_wcd_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/soc/swr_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/dsp/q6_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/soc/swr_ctrl_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/dsp/q6_pdr_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/dsp/q6_notifier_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/ipc/gpr_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/dsp/spf_core_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/dsp/audio_prm_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/dsp/audpkt_ion_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/ipc/audio_pkt_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/dsp/adsp_loader_dlkm.ko
	echo 1 > /sys/kernel/boot_adsp/boot
	insmod $MODULE_BASE/kernel/techpack/audio/asoc/codecs/stub_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/asoc/platform_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/asoc/codecs/wcd_core_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/asoc/codecs/mbhc_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/asoc/codecs/wcd9xxx_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/asoc/codecs/wsa881x_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/asoc/codecs/wcd934x/wcd934x_dlkm.ko
	insmod $MODULE_BASE/kernel/techpack/audio/asoc/machine_dlkm.ko


        echo "done loading audio_kernel module"
        ;;
  stop)
        echo -n "Bypassing Unloading of  audio_kernel modules "
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
