#SPDX-License-Identifier: GPL-2.0-only
#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
q6_pdr_dlkm
q6_notifier_dlkm
q6_dlkm
snd_event_dlkm
gpr_dlkm
spf_core_dlkm
audpkt_ion_dlkm
audio_pkt_dlkm
adsp_loader_dlkm
audio_prm_dlkm
pinctrl_lpi_dlkm
swr_dlkm
stub_dlkm
wcd_core_dlkm
wcd9xxx_dlkm
wcd938x_slave_dlkm
wsa883x_dlkm
swr_ctrl_dlkm
mbhc_dlkm
wcd938x_dlkm
swr_dmic_dlkm
swr_haptics_dlkm
lpass_cdc_dlkm
lpass_cdc_rx_macro_dlkm
lpass_cdc_tx_macro_dlkm
lpass_cdc_va_macro_dlkm
lpass_cdc_wsa2_macro_dlkm
lpass_cdc_wsa_macro_dlkm
wsa884x_dlkm

