#Conf file to load audio-driver modules at boot-up time
#Install under /etc/modules-load-d/ path
apr_dlkm
q6_dlkm
platform_dlkm
native_dlkm
mbhc_dlkm
stub_dlkm
wcd9xxx_dlkm
wcd9330_dlkm
swr_ctrl_dlkm
machine_dlkm

