#! /bin/sh
# Copyright (c) 2019, 2020 The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Changes from Qualcomm Innovation Center, Inc. are provided under the following license:
# Copyright (c) 2022-2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#

export MODULE_BASE=/lib/modules/`uname -r`/
set -e

case "$1" in
  start)
        echo -n "Starting/Loading audio module: "

        echo "audio:start/load" > /dev/kmsg
        insmod /lib/modules/audio/snd_event_dlkm.ko
        insmod /lib/modules/audio/q6_notifier_dlkm.ko
        insmod /lib/modules/audio/apr_dlkm.ko
        insmod /lib/modules/audio/adsp_loader_dlkm.ko
        insmod /lib/modules/audio/stub_dlkm.ko
        echo 1 > /sys/kernel/boot_adsp/boot
        insmod /lib/modules/audio/q6_dlkm.ko
        insmod /lib/modules/audio/platform_dlkm.ko
        insmod /lib/modules/audio/native_dlkm.ko
        insmod /lib/modules/audio/wcd_core_dlkm.ko
        insmod /lib/modules/audio/wcd9xxx_dlkm.ko
        insmod /lib/modules/audio/wcd9330_dlkm.ko
        insmod /lib/modules/audio/machine_dlkm.ko
        insmod /lib/modules/audio/pinctrl_wcd_dlkm.ko
        insmod /lib/modules/audio/mbhc_dlkm.ko
        insmod /lib/modules/audio/swr_dlkm.ko
        insmod /lib/modules/audio/swr_ctrl_dlkm.ko

        echo "done loading audio_kernel module"
        ;;
  stop)
        echo "Unloading of audio_kernel modules "  > /dev/kmsg
        rmmod swr_ctrl_dlkm
        rmmod swr_dlkm
        rmmod mbhc_dlkm
        rmmod pinctrl_wcd_dlkm
        rmmod machine_dlkm
        rmmod wcd9330_dlkm
        rmmod wcd9xxx_dlkm
        rmmod wcd_core_dlkm
        rmmod native_dlkm
        rmmod platform_dlkm
        rmmod q6_dlkm
        echo "audio: unvoting for adsp" > /dev/kmsg
        echo 0 > /sys/kernel/boot_adsp/boot
        echo "Unloading adsp_loader and apr" > /dev/kmsg
        rmmod stub_dlkm
        rmmod adsp_loader_dlkm
        rmmod apr_dlkm
        rmmod q6_notifier_dlkm
        rmmod snd_event_dlkm

        echo -n "Unloading audio_kernel modules completed"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0

