BBFILES += "${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-audio"
BBFILE_PRIORITY_qti-audio = "20"
BBFILE_PATTERN_qti-audio := "^${LAYERDIR}/"
LAYERDEPENDS_qti-audio := "\
   core \
   qti-bsp"
LAYERSERIES_COMPAT_qti-audio = "dunfell scarthgap"
LAYERVERSION_qti-audio = "1"
