BBFILES += "${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend ${LAYERDIR}/recipes-*/*/*.bb"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-audio"
BBFILE_PRIORITY_qti-audio = "20"
BBFILE_PATTERN_qti-audio := "^${LAYERDIR}/"
LAYERDEPENDS_qti-audio := "\
   core \
   qti-bsp"
LAYERSERIES_COMPAT_qti-audio = "kirkstone"
LAYERVERSION_qti-audio = "1"


BBMASK += "audiohal_1.0.bb \
           encoders_1.0.bb \
           qahw_git.bb \
           usbaudio_git.bb \
           csd-server_git.bb \
          "
