#Conf file to load audio-driver modules at boot-up time
#Install under /etc/modules-load-d/ path
q6_notifier_dlkm
apr_dlkm
adsp_loader_dlkm
q6_dlkm
platform_dlkm
native_dlkm
swr_dlkm
stub_dlkm
wsa881x_analog_dlkm
machine_dlkm
pinctrl_lpi_dlkm
bolero_cdc_dlkm
pm2250_spmi_dlkm
va_macro_dlkm
rx_macro_dlkm
tx_macro_dlkm
machine_dlkm
rouleur_dlkm
rouleur_slave_dlkm