#! /bin/sh
# Copyright (c) 2019, 2020 The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


export MODULE_BASE=/lib/modules/`uname -r`/
set -e

case "$1" in
  start)
        echo -n "Starting/Loading audio module: "

        echo "audio:start/load" > /dev/kmsg
        modprobe adsp_loader_dlkm
        echo 1 > /sys/kernel/boot_adsp/boot
        modprobe q6_pdr_dlkm
        modprobe q6_notifier_dlkm
        modprobe snd_event_dlkm
        modprobe apr_dlkm
        modprobe q6_dlkm
        modprobe native_dlkm
        modprobe pinctrl_lpi_dlkm
        modprobe swr_dlkm
        modprobe platform_dlkm
        modprobe stub_dlkm
        modprobe wsa881x_analog_dlkm
        modprobe bolero_cdc_dlkm
        modprobe va_macro_dlkm
        modprobe rx_macro_dlkm
        modprobe tx_macro_dlkm
        modprobe pm2250_spmi_dlkm
        modprobe rouleur_dlkm
        modprobe rouleur_slave_dlkm
        modprobe machine_dlkm
        echo "done loading audio_kernel module" > /dev/kmsg
        ;;
  stop)
        echo -n "Bypassing Unloading of  audio_kernel modules "
        echo 0 > /sys/kernel/boot_adsp/boot
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
