#!/bin/sh /etc/rc.common

#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear.

START=30
STOP=69

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /etc/initscripts/start_audio_le
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
}

stop_service() {
	echo "Stopping init_qcom_audio:"
	# commands to kill application
}
