#Conf file to load audio-driver modules at boot-up time
#Install under /etc/modules-load-d/ path
q6_pdr_dlkm
q6_notifier_dlkm
snd_event_dlkm
apr_dlkm
adsp_loader_dlkm
q6_dlkm
pinctrl_wcd_dlkm
pinctrl_lpi_dlkm
swr_dlkm
platform_dlkm
hdmi_dlkm
stub_dlkm
wcd_core_dlkm
wsa883x_dlkm
bolero_cdc_dlkm
swr_haptics_dlkm
swr_ctrl_dlkm
tx_macro_dlkm
mbhc_dlkm
wcd9xxx_dlkm
wcd937x_dlkm
wcd938x_dlkm
wcd938x_slave_dlkm
wcd937x_slave_dlkm
wsa_macro_dlkm
va_macro_dlkm
rx_macro_dlkm
swr_dmic_dlkm
native_dlkm
machine_dlkm
slimbus-ngd
