#Conf file to load audio-driver modules at boot-up time
#Install under /etc/modules-load-d/ path
q6_pdr_dlkm
q6_notifier_dlkm
snd_event_dlkm
gpr_dlkm
adsp_loader_dlkm
q6_dlkm
pinctrl_wcd_dlkm
pinctrl_lpi_dlkm
swr_dlkm
platform_dlkm
hdmi_dlkm
stub_dlkm
wcd_core_dlkm
wsa881x_dlkm
wcd9xxx_dlkm
bolero_cdc_dlkm
wsa_macro_dlkm
va_macro_dlkm
rx_macro_dlkm
tx_macro_dlkm
wcd938x_dlkm
wcd938x_slave_dlkm
machine_dlkm
audpkt_ion_dlkm
audio_pkt_dlkm
audio_prm_dlkm
mbhc_dlkm
voice_mhi_dlkm
spf_core_dlkm
swr_ctrl_dlkm
